project:
  type: website

website:
  title: "VAA-Project-G6"

      
  sidebar:
    logo: "fishing.jpg"
    pinned: true
    align: center
    search: true
    collapse-level: 1
    contents: 
      - text: Home
        href: index.qmd
      - text: "Project Proposal"
        href: "Proposal/Proposal.qmd"
      - text: User Guide
        href: 
      - text: Application
        href: 
      - text: Poster
        href:


format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    layout: _layout.html

editor: visual
