project:
  type: website

website:
  page-navigation: false
  title: "VAA-Project-G6"
  
  page-footer:
    right: "ISSS608 VAA Project"
  
  sidebar:
    logo: "fishing.jpg"
    pinned: true
    align: center
    tools: 
      - icon: "server"
        href: https://vast-challenge.github.io/2023/MC2.html
        text: "Data Source"
      
      - icon: "display"
        href: https://yangty.shinyapps.io/VAA-ShinyAPP/
        text: "R Shiny Application"
      
      - icon: github
        href: https://github.com/yangty54/VAA-Project-G6
        text: "GitHub Repository"
    
    style: "docked"
    search: true
    collapse-level: 1
    
    contents: 
      - text: Home
        href: index.qmd
      - text: "Overview"
        href: "Overview.qmd"
      - text: User Guide
        href: "UserGuide.qmd"
      - text: Application
        href: "Application.qmd"
      - text: Poster
        href:

format:
  html:
    theme: Journal
    css: styles.css
    toc: true
    code-overflow: wrap
    page-layout: full

editor: visual
