project:
  type: website

website:
  page-navigation: false
  title: "VAA-Project-G6"
  site-url: "https://vaa-project-g6.netlify.app/"
  repo-url: "https://github.com/yangty54/VAA-Project-G6"
  
  page-footer:
    right: "ISSS608 VAA Project"
  
  sidebar:
    logo: "fishing.jpg"
    pinned: true
    align: center
    tools: 
      - icon: "server"
        href: https://vast-challenge.github.io/2023/MC2.html
        text: "Data Source"
      
      - icon: "display"
        href: https://yangty.shinyapps.io/VAA-ShinyAPP/
        text: "R Shiny Application"
      
      - icon: github
        href: https://github.com/yangty54/VAA-Project-G6
        text: "GitHub Repository"
    
    style: "docked"
    search: true
    collapse-level: 1
    
    contents: 
      - text: "{{< bi house-fill >}} Home"
        href: index.qmd
      - text: "{{< bi text-paragraph >}} Project Overview"
        href: "Overview.qmd"
      - text: "{{< bi file-earmark-richtext-fill >}} User Guide"
        href: "UserGuide.qmd"
      - text: "{{< bi window-sidebar >}} Application"
        href: "Application.qmd"
      - text: "{{< bi easel >}} Poster"
        href: "poster.qmd"

format:
  html:
    theme: Journal
    css: styles.css
    toc: true
    code-overflow: wrap
    page-layout: full

editor: visual
