project:
  type: website

website:
  title: "VAA-Project-G6"
      
  sidebar:
    logo: "fishing.jpg"
    pinned: true
    align: center
    tools: 
      - icon: "server"
        href: https://vast-challenge.github.io/2023/MC2.html
        text: "Data Source"
      
      - icon: "display"
        href: https://github.com/yangty54
        text: "R Shiny Application"
      
      - icon: github
        href: https://github.com/yangty54/VAA-Project-G6
        text: "GitHub Repository"
    search: true
    collapse-level: 1
    contents: 
      - text: Home
        href: index.qmd
      - text: "Proposal"
        href: "Proposal/Proposal.qmd"
      - text: User Guide
        href: 
      - text: Application
        href: 
      - text: Poster
        href:

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    layout: _layout.html

editor: visual
