project:
  type: website

website:
  title: "VAA-Project-G6"
  navbar:
    left: 
      - text: "Project Proposal"
        href: "Proposal/Proposal.qmd"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual